development:
  validation_framework: :active_model #optional
  database: cmtool
test:
  validation_framework: :active_model #optional
  database: cmtool
production:
  validation_framework: :active_model #optional
  database: cmtool
